# Generated by Django 4.0.3 on 2022-03-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_sendregistr'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendregistr',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
